config/routes.rb
Homework2::Application.routes.draw do
  get 'admin' => 'admin#index'
     controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
     end
  get "sessions/create"
  get "sessions/destroy"
  resources :users

  resources :tasks

  

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
  
  after_destroy :ensure_an_admin_remains
  private
      def ensure_an_admin_remains
          if User.count.zero?
              raise "Последний пользователь не может быть удален"
  end end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
      @total_tasks = Task.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authorize
 protected
          def authorize
              unless User.find_by(id: session[:user_id])
              redirect_to login_url, notice: "Please sign in"
 end end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new
  end

  def create
      user = User.find_by(name: params[:name])
      if user and user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to tasks_url
      else
         redirect_to login_url, alert: "Check your name or password"    end
  end

  def destroy
      session[:user_id] = nil
         redirect_to login_url, notice: "You are log out"
  end
  def register
  redirect_to :controller => 'users', :action => 'create'
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :descripyion)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorize
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to tasks_url, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
      begin
          @user.destroy
          flash[:notice] = "User has been #{@user.name} deleted"
      rescue StandardError => e
          flash[:notice] = e.message
      end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<div class="container">
<body>
<div class="container">
	 <% if session[:user_id] %>
	 
<nav class="navbar navbar-inverse navbar-top">
	 <a class="navbar-brand" href="#">Task manager</a>
      <div class="container">
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
           
	    <li class="active"><a href="tasks">Tasks</a></li>
	    
            <li><a href="users">Users</a></li>
	    <li><a href="#"> </a></li>
	     <li><a href="#"> </a></li>
	      <li><a href="#"> </a></li>
	       <li><a href="#"> </a></li>
	      <li><a href="#"> </a></li>
	        <li><a href="#"> </a></li>
	      <li><a href="#"> </a></li>
          <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li><li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  <li><a href="#"> </a></li>
	  
	      <li>     
	       <%= button_to 'Logout', logout_path, method: :delete, class: 'btn btn-sm btn-info' %>
	      </li>
	    
        </div>
	
	      
	
</div>
 </nav>
  <% end %>
 </div>
 
 
<%= yield %>


</body>

</div>

</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    
    <%= f.text_area :descripyion, class:'form-control' %>
  </div>
   <button class="btn btn-lg btn-primary btn-block" type="submit">
	Create task
	   </button>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h2 id="tables-bordered">Manager tasks</h2>
<div class="bs-example">
    <table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
	      
        <td><%= task.name %></td>
        <td><%= task.descripyion %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<%= link_to 'New Task', new_task_path,class:"btn btn-info" %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Descripyion:</strong>
  <%= @task.descripyion %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<div class="form-signin">
 <%= form_for @user do |f| %>
     <% if @user.errors.any? %>
     <div id="error_explanation">
                 <h2><%= pluralize(@user.errors.count, "error") %> , data can`t be saved:</h2>
                 <ul>
                 <% @user.errors.full_messages.each do |msg| %>
                     <li><%= msg %></li>
     <% end %>
     </ul> </div>
     <% end %>
        <div class="container">
     <fieldset>
         <legend>Enter your data</legend>
         <div class="field">
            <%= f.label :name, 'Name:' %>
            <%= f.text_field :name, size: 40,class:'form-control' %>
     </div>
         <div class="field">
             <%= f.label :password, 'Password:' %>:
             <%= f.password_field :password, size: 40,class:'form-control' %>
     </div>
         <div class="field">
             <%= f.label :password_confirmation, 'Reenter your password:' %>:
             <%= f.password_field :password_confirmation, size: 40,class:'form-control' %>
     </div>
          <button class="btn btn-lg btn-primary btn-block" type="submit">
		  Sign up
		   </button>
         </fieldset>
     <% end %>
     </div>
    </div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2 id="tables-bordered">Listing users</h2>

<% if notice %>
   <p id="notice"><%= notice %></p>
   <% end %>
<div class="container">
<div class="bs-example">
    <table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
</div>

<div class="container">

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>